# MC Paint mod definition file
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[25,26)" #mandatory
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ichttt/mcpaint" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecraft.curseforge.com/projects/mc-paint" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="mcpaint_logo.png" #optional
# A text field displayed in the mod UI
authors="ichttt" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="mcpaint" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.3.2" #mandatory
 # A display name for the mod
displayName="Mc Paint" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Paint your blocks the way you want them to be!

The mod adds two items, a brush and a stamp. The brush can be crafted like a pickaxe but with wool instead of your pickaxe material at the top.
Right-click any block with the brush and a editor will pop up where you can paint it!
The resolution can be changed from 8x8 up to 128x128 for a single block.
'''